#KubeJS Dev Properties
#Tue Apr 14 02:48:24 MSK 2026
alwaysCaptureErrors=false
dataPackOutput=false
debugInfo=true
logAddedRecipes=false
logErroringRecipes=true
logGeneratedData=false
logInvalidRecipeHandlers=true
logModifiedRecipes=false
logRemovedRecipes=false
logSkippedPlugins=true
logSkippedRecipes=false
logSkippedTags=false
strictTags=false
